Minor: Remove unneeded includes
This fixes a common compile error on the CI I think:

```
In file included from
/home/jenkins/sources/kdev-php/latest-qt4/duchain/tests/duchaintestbase.cpp:213:0:
/home/jenkins/sources/kdev-php/latest-qt4/build/completion/tests/duchaintestbase.moc:44:11:
error: 'Php::Php' has not been declared
```

(cherry picked from commit 92573251bcf088c3557892816542df1e714ba51f)